### ISSUE TITLE
CUDA not found

### ISSUE THREAD

**Issue by MrDotOne** [broadinstitute/CellBender#117]
I have pulled the latest docker image from GCR and i have also built the docker by hand and when running cellbender with --cuda i continually get 

Traceback (most recent call last):
  File "/home/user/miniconda/bin/cellbender", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "/cellbender/cellbender/base_cli.py", line 98, in main
    args = cli_dict[args.tool].validate_args(args)
  File "/cellbender/cellbender/remove_background/cli.py", line 69, in validate_args
    assert torch.cuda.is_available(), "Trying to use CUDA, " \
AssertionError: Trying to use CUDA, but CUDA is not available.

I am running this on a GPU HPC node. When investigating i note that the /usr/local/cuda seems rather sparse to me from my experience. All that is there is lib64 and even that there is only one SO. So how does one go about running this on a gpu node using the gpu-enabled docker image?

This is the command i am attempting to run in the container
#!/bin/bash

cellbender remove-background \
--input raw_feature_bc_matrix.h5 \
--output cellbender.h5 \
--expected-cells 10000 \
--epochs 150 \
--total-droplets-included 20000 \
--learning-rate 1e-4 \
--fpr 0.01 \
--cuda

**Comment by sjfleming** [comment]
Hi @MrDotOne ,

It is possible that my docker image is getting a bit old now... I am planning to update it soon.
What do I mean by that?

Nvidia keeps updating their GPU drivers, and some versions of CUDA are only compatible with some Nvidia driver versions.  I think that's probably what's happening to you.  I have run into it recently myself.

My recommendations for you:
If you are running on a GPU HPC node, then check which Nvidia driver version you have.  If you want to use a docker image, then I would recommend this updated Dockerfile (the update is the newer CUDA base image from Nvidia... I will probably merge this soon):

```
# Start from nvidia-docker image with drivers pre-installed to use a GPU
FROM nvcr.io/nvidia/cuda:11.3.1-base-ubuntu16.04

LABEL maintainer="Stephen Fleming <sfleming@broadinstitute.org>"

# Install curl and sudo and git and miniconda
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    sudo \
 && sudo apt-get install -y --no-install-recommends \
    git \
    bzip2 \
 && sudo rm -rf /var/lib/apt/lists/* \
 && curl -so ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p /home/user/miniconda \
 && rm ~/miniconda.sh

ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# google cloud SDK and gsutil and pytorch and pytables
RUN curl -sSL https://sdk.cloud.google.com | bash \
 && conda install -y -c conda-forge google-api-python-client oauth2client google-auth \
    google-cloud-sdk google-auth-oauthlib \
 && conda install -y pytorch==1.8.0 torchvision==0.9.0 cudatoolkit=10.2 -c pytorch \
 && conda install -y -c anaconda pytables==3.6.1 \
 && conda clean -ya

ENV DOCKER='true'

RUN git clone https://github.com/broadinstitute/CellBender.git cellbender \
 && yes | pip install -e cellbender \
 && sudo rm -rf ~/.cache/pip

# Add cellbender command to PATH
ENV PATH="~/miniconda/bin:${PATH}"
```

**Comment by MrDotOne** [comment]
I feel i am doing something wrong here, i still get the error even after building the new container

root@bae3ab6b940e:/home/mweiner/beegfs# cellbender remove-background --input raw_feature_bc_matrix.h5 --output cellbender.h5 --expected-cells 10000 --epochs 150 --total-droplets-included 20000 --learning-rate 1e-4 --fpr 0.01 --cuda
Traceback (most recent call last):
  File "/home/user/miniconda/bin/cellbender", line 11, in <module>
    load_entry_point('cellbender', 'console_scripts', 'cellbender')()
  File "/cellbender/cellbender/base_cli.py", line 98, in main
    args = cli_dict[args.tool].validate_args(args)
  File "/cellbender/cellbender/remove_background/cli.py", line 69, in validate_args
    assert torch.cuda.is_available(), "Trying to use CUDA, " \
AssertionError: Trying to use CUDA, but CUDA is not available.

**Comment by sjfleming** [comment]
Hmmmm... I wish I was better at diagnosing these kinds of things... It looks like, outside the docker container when you run `nvidia-smi`, you see that you have CUDA 11.0 installed.

Actually I may have made a mistake in that previous Dockerfile... it looks like I have a base image with CUDA 11.3 but then pytorch with the 10.2 cuda toolkit.  That may have been my mistake there.  Just to be safe, since your `nvidia-smi` worked with CUDA 11.0, let's use that version.  Can you try this Dockerfile?

```
# Start from nvidia-docker image with drivers pre-installed to use a GPU
FROM nvcr.io/nvidia/cuda:11.0.3-base-ubuntu16.04

LABEL maintainer="Stephen Fleming <sfleming@broadinstitute.org>"

# Install curl and sudo and git and miniconda
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    sudo \
 && sudo apt-get install -y --no-install-recommends \
    git \
    bzip2 \
 && sudo rm -rf /var/lib/apt/lists/* \
 && curl -so ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p /home/user/miniconda \
 && rm ~/miniconda.sh

ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# google cloud SDK and gsutil and pytorch and pytables
RUN curl -sSL https://sdk.cloud.google.com | bash \
 && conda install -y -c conda-forge google-api-python-client oauth2client google-auth \
    google-cloud-sdk google-auth-oauthlib \
 && conda install -y pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch \
 && conda install -y -c anaconda pytables==3.6.1 \
 && conda clean -ya

ENV DOCKER='true'

RUN git clone https://github.com/broadinstitute/CellBender.git cellbender \
 && yes | pip install -e cellbender \
 && sudo rm -rf ~/.cache/pip

# Add cellbender command to PATH
ENV PATH="~/miniconda/bin:${PATH}"
```

**Comment by prete** [comment]
Hi @MrDotOne  what's does your `docker run` command look like?
You might be:
(a) missing the [`--gpus all`](https://docs.docker.com/engine/reference/commandline/run/#access-an-nvidia-gpu) to enable GPU inside the container and thus breaking something in CUDA or
(b) binding external volumes to the container on paths which have specific libs needed

**Comment by MrDotOne** [comment]
I will try that, thank you.

**Comment by MrDotOne** [comment]
Actually i pulled the 'official' container down rather than build and that seems to have resolved my issue for the moment. I threw it over the wall to the researcher so they could run it and see if they run into any issues.

Thank you
Michael
