### ISSUE TITLE
Batch size, CUDA out of memory

### ISSUE THREAD

**Issue by Elhl93** [broadinstitute/CellBender#67]
Hi, 

Great package! I am currently using cellbender V2.1. I ran into an issue, which is caused by too high memory allocation. 

```
[....]
cellbender:remove-background: [epoch 198]  average training loss: 1790.0774
cellbender:remove-background: [epoch 199]  average training loss: 1787.5904
cellbender:remove-background: [epoch 200]  average training loss: 1792.2732
cellbender:remove-background: [epoch 200] average test loss: 1773.5361
cellbender:remove-background: Inference procedure complete.
cellbender:remove-background: 2020-08-06 23:06:51
cellbender:remove-background: Preparing to write outputs to file...
cell counts tensor([ 8096.,  6134.,  1805.,  2324.,  5410.,  5546.,  5092.,  1724.,  5301.,
         1329.,  3143.,  5382.,   618.,  3833.,  6279.,  5066.,  2166.,  7982.,
         7920.,  3160.,  3907., 12285.,  3919.,  7285.,  1576.,  2011.,  1805.,
         5842.,  2688.,  8696.,  7202.,  7752.,  6153.,  4572.,  2058.,  7318.,
         3196.,  3786.,  7375.,  2877.,  2555.,  4179.,  1650.,  1776.,  4262.,
         4624.,  5314.,  5727.,  5470.,   693.,  4088.,  2078.,  1429.,  2127.,
         5265.,   649.,  4733.,  9864., 19365.,  7845.,  5621.,   699.,  3006.,
         3918.,  1308.,  6071.,  5948.,  1816.,  7495.,  3055.,  2016., 11080.,
         1845.,  1077., 14801.,  8278.,  2293.,  1718.,  1436.,  7260.,  1655.,
        13636.,  8505.,  1307.,  2211.,  7010.,  4465.,  1496.,  3346.,  8285.,
         1948.,  1978.,  2007.,  1693., 16839.,  6170.,  4675., 12212.,  1955.,
         1499.], device='cuda:0')
Traceback (most recent call last):
  File "path/to/bin/cellbender", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "path/to/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "path/to/cellbender/remove_background/cli.py", line 103, in run
    main(args)
  File "path/to/cellbender/remove_background/cli.py", line 196, in main
    run_remove_background(args)
  File "path/to/cellbender/remove_background/cli.py", line 166, in run_remove_background
    save_plots=True)
  File "path/to/cellbender/remove_background/data/dataset.py", line 524, in save_to_output_file
    inferred_count_matrix = self.posterior.mean
  File "path/to/cellbender/remove_background/infer.py", line 56, in mean
    self._get_mean()
  File "path/to/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "path/to/cellbender/remove_background/infer.py", line 402, in _get_mean
    alpha_est=map_est['alpha'])
  File "path/to/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "path/to/cellbender/remove_background/infer.py", line 1005, in _lambda_binary_search_given_fpr
    alpha_est=alpha_est)
  File "path/to/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "path/to/cellbender/remove_background/infer.py", line 809, in _calculate_expected_fpr_given_lambda_mult
    alpha_est=alpha_est)
  File "path/to/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "path/to/cellbender/remove_background/infer.py", line 604, in _true_counts_from_params
    .log_prob(noise_count_tensor)
  File path/to/lib/python3.7/site-packages/torch/distributions/poisson.py", line 63, in log_prob
    return (rate.log() * value) - rate - (value + 1).lgamma()
RuntimeError: CUDA out of memory. Tried to allocate 1016.00 MiB (GPU 0; 3.97 GiB total capacity; 2.48 GiB already allocated; 378.79 MiB free; 2.58 GiB reserved in total by PyTorch)
```

Do you suggest to change environmental settings, or adjust the batch size? Changing "empty-drop-training-fraction" did not solve the issue. Thanks for your thoughts!

**Comment by sjfleming** [comment]
Thanks!

I have a couple questions for you:
1. How much GPU memory do you have?  I typically work with a Tesla K80 that has (I think) 15GB of GPU memory.  It looks like maybe you are running on a GPU with less memory?
2. How many genes does your dataset have?  (It should be around line 8 in the CellBender log file)

Interesting, I see that the inference procedure has completed.  It looks like it's during posterior generation that this memory error occurs.  Unfortunately that is a place where I've currently got something hard-coded that you can't change by modifying an input parameter.

If you want to reach into the code to try to make this work, I would suggest that you do the following with your own local copy of the cellbender code:

https://github.com/broadinstitute/CellBender/blob/0feb5e0f8867332d3c55711e4390dd4f5b03fa18/cellbender/remove_background/infer.py#L413

I would change this line to `batch_size=5`.  It may create the posterior a bit more slowly, but at least it should help you get an output.

**Comment by mtvector** [comment]
Love this hack idea, I've also run into the same problem on some GPUs, would be cool to have a parameter a user can input depending on the vram the GPUs they have access to so they can run :)

**Comment by Elhl93** [comment]
Thanks for your response! 

1. You are right, my GPU is in comparison small. I work with a Tesla GRID T4-4Q with ~4G. 
2. As input I use a 10X dataset "raw_feature_bc_matrix.h5" with ~33.5k genes. Expected cells I have 5000, total-droplets-included 15000 and epochs 10 (during testing). Cellbender returns the following: 
cellbender:remove-background: Including 26750 genes that have nonzero counts.
cellbender:remove-background: Using 5000 probable cell barcodes, plus an additional 10000 barcodes, and 72667 empty droplets.

As you suggested I changed the batch size to 5 and 3, but the error keeps showing up. I also changed the batch size in "self.dataset_obj.get_dataloader" from 500 to 300 and checked wether I can free some reusable memory with torch.cuda.empty_cache() immediately after "Preparing to write outputs to file..." is printed, but all not successful.

**Comment by sjfleming** [comment]
I will take another look!

**Comment by sjfleming** [comment]
Ah, okay, try changing this line

https://github.com/broadinstitute/CellBender/blob/0feb5e0f8867332d3c55711e4390dd4f5b03fa18/cellbender/remove_background/infer.py#L383

try changing `100` to `25`

**Comment by heathergeiger** [comment]
@sjfleming any update on this? Just ran into the same issue.

The corresponding line you refer to in the source code is now on line 351, and reads min(consts.CELLS_POSTERIOR_REG_CALC, cell_inds.size).

**Comment by YubinXie** [comment]
I have the same issue, and my GPU has 12G memory.

**Comment by smorabit** [comment]
I just got the same CUDA out of memory issue as well. I would love to know a workaround for this, since I am very interested in using this tool in my research! The GPU that I am using has 8GB of memory.

```
cellbender:remove-background: Inference procedure complete.
cellbender:remove-background: 2021-04-06 14:13:44
cellbender:remove-background: Preparing to write outputs to file...
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/CellBender/bin/cellbender", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/cli.py", line 103, in run
    main(args)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/cli.py", line 196, in main
    run_remove_background(args)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/cli.py", line 166, in run_remove_background
    save_plots=True)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/data/dataset.py", line 530, in save_to_output_file
    inferred_count_matrix = self.posterior.mean
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/infer.py", line 58, in mean
    self._get_mean()
  File "/home/jovyan/.conda/envs/CellBender/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/infer.py", line 368, in _get_mean
    alpha_est=map_est['alpha'])
  File "/home/jovyan/.conda/envs/CellBender/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/infer.py", line 713, in _lambda_binary_search_given_fpr
    alpha_est=alpha_est)
  File "/home/jovyan/.conda/envs/CellBender/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/infer.py", line 653, in _calculate_expected_fpr_given_lambda_mult
    alpha_est=alpha_est)
  File "/home/jovyan/.conda/envs/CellBender/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/dfs3b/swaruplab/smorabit/bin/software/CellBender/cellbender/remove_background/infer.py", line 569, in _true_counts_from_params
    .log_prob(data.unsqueeze(-1) - noise_count_tensor))
  File "/home/jovyan/.conda/envs/CellBender/lib/python3.7/site-packages/torch/distributions/negative_binomial.py", line 95, in log_prob
    log_normalization = (-torch.lgamma(self.total_count + value) + torch.lgamma(1. + value) +
RuntimeError: CUDA out of memory. Tried to allocate 1.01 GiB (GPU 0; 7.93 GiB total capacity; 6.53 GiB already allocated; 900.56 MiB free; 6.57 GiB reserved in total by PyTorch)
```

**Comment by YubinXie** [comment]
> Thanks!
> 
> I have a couple questions for you:
> 
> 1. How much GPU memory do you have?  I typically work with a Tesla K80 that has (I think) 15GB of GPU memory.  It looks like maybe you are running on a GPU with less memory?
> 2. How many genes does your dataset have?  (It should be around line 8 in the CellBender log file)
> 
> Interesting, I see that the inference procedure has completed. It looks like it's during posterior generation that this memory error occurs. Unfortunately that is a place where I've currently got something hard-coded that you can't change by modifying an input parameter.
> 
> If you want to reach into the code to try to make this work, I would suggest that you do the following with your own local copy of the cellbender code:
> 
> https://github.com/broadinstitute/CellBender/blob/0feb5e0f8867332d3c55711e4390dd4f5b03fa18/cellbender/remove_background/infer.py#L413
> 
> I would change this line to `batch_size=5`. It may create the posterior a bit more slowly, but at least it should help you get an output.

This works on my case.

**Comment by sjfleming** [comment]
@heathergeiger @smorabit 
Let me know if the change that @YubinXie copied above does not work for you.  I think that is the problem.

In my next commit, I will definitely include a command-line input parameter so that this can be controlled without having to reach into the code.

**Comment by sjfleming** [comment]
Moving this to #98

**Comment by smorabit** [comment]
So I tried changing the batch size to 5 as suggested above, but I got the same error. However, after looking at #98, I tried to change the n_cells parameter to 10 rather than 100 (not sure if this is too low?) and with that it was able to finish running.

**Comment by whitleyo** [comment]
Hello,

I've encountered memory related issues with CellBender similar to that described here, but after specifying the posterior batch size option:

```
cellbender:remove-background: [epoch 009]  average training loss: 18918.2091
    return super().log_prob(value)
  File "/home/whitleyo/.local/lib/python3.9/site-packages/torch/distributions/poisson.py", line 63, in log_prob
    return value.xlogy(rate) - rate - (value + 1).lgamma()RuntimeError: CUDA out of memory. Tried to allocate 9.28 GiB (GPU 0; 31.75 GiB total capacity; 23.22 GiB already allocated; 6.83 GiB free; 23.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "./src/decontam_utils.py", line 331, in run_decontam_each
    assert exit_code == 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cli_run.py", line 127, in <module>
    run_pipeline()
  File "{conda_env}/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "{conda_env}/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "{conda_env}/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "{conda_env}/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./src/cli_run.py", line 107, in run_pipeline
    dc.run_all_steps(file_list=file_list, 
  File "./src/decontam_utils.py", line 69, in run_all_steps
    run_summary_fpath = run_decontam_each(file_list=file_list, 
  File "./src/decontam_utils.py", line 341, in run_decontam_each
    raise Exception(msg_exit_code)            
Exception: command exited with status 256 for combined_id XXX command: cellbender remove-background --input /scratch/CellBender/decontam/XXX/raw_feature_bc_matrix.h5 --output /scratch/CellBender/decontam/XXX/output.h5  --cuda   --expected-cells 7384 --total-droplets-included 15384 --p
osterior-batch-size 10 --fpr 0.01 --epochs 80
```

Note that some filepaths have been edited. 

The data itself is pretty vanilla (~8000 cells and droplets thereafter). I suspect that there may be issues with batch_size set for training, which appears to be a separate variable from posterior batch size.

![image](https://github.com/broadinstitute/CellBender/assets/25909144/858f606c-4f21-4199-b83d-7044581d1854)


If this is the case, I'm wondering if it would be worthwhile to add another command line argument for training batch size.

**Comment by sjfleming** [comment]
Hi @whitleyo , this is something I'd definitely want to get working for you.  I have not seen anyone run into this error yet.  Yes, you are running out of CUDA memory in the middle of training, after 9 epochs.  I find this very strange... since I'd expect CUDA memory usage during training to be constant (and that is indeed what I see if I watch memory usage when I run cellbender).

A couple of questions:
- What GPU are you using?  Something from Nvidia, like Nvidia T4?  How much GPU memory is there?
- How many features (genes plus any other modality) are in your dataset?  The only thing I can think is if this is a dataset with gene expression and like 100k+ ATAC peaks, then maybe you're running into problems with CUDA memory... but I still don't know why it would work for the first 9 epochs and then have a problem...
- Which version of `pyro` and `pytorch` are you using?

**Comment by whitleyo** [comment]
1. NVIDIA Volta. 32GB RAM
2. About 200,000. It turns out that my script wasn't properly subsetting for RNA features before hand
3. pyro 1.8.4, pytorch 1.11.0.
I think 2 is the most relevant, since I solved that issue and it seems I make it past epoch 10 this time around. Still waiting for my job to finish

For now I think we can consider my comment closed

**Comment by sjfleming** [comment]
Hi @whitleyo , excellent, thanks for letting me know!

**Comment by zhijunyuu** [comment]
Hello CellBender team, 

Very nice tool!
Recently I ran into the error of `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.54 GiB (GPU 0; 19.50 GiB total capacity; 17.24 GiB already allocated; 904.94 MiB free;` during `Working on chunk (2/135)`
I am using v 0.3.0 cellbender on python3.8.
I tried to change the batch_size to 20 and 5, both did not work and I got the same error every time. 
Do you have any idea what I could do to solve the problem? Thanks in advance!

Best, 
Zhijun

**Comment by sjfleming** [comment]
Hi @zhijunyuu , sorry you're running into that... hmmm, are you using the code on the `sf_dev_0.3.0_postreg` branch?  I was hoping these kinds of errors would be a lot less likely with the latest updates.  Can you tell me a little bit more about the dataset (or post the log file)?  How many features (genes and anything else) are included in the analysis?

**Comment by zhijunyuu** [comment]
Hello, 

Thanks for the reply, I have `CellBender 0.3.0` and 10xMultiome data as input. Here is the log file

[out_cellbender.txt](https://github.com/broadinstitute/CellBender/files/12011655/out_cellbender.txt)

where could I get the `sf_dev_0.3.0_postreg` branch? Maybe I  could have a try on that one.

**Comment by sjfleming** [comment]
Hi @zhijunyuu , it looks like you are already using that `sf_dev_0.3.0_postreg` branch, potentially, based on the log file.  You can make sure you have the latest version of the changes on that branch by following this:

https://github.com/broadinstitute/CellBender/issues/225#issuecomment-1667976108

I would suggest two potential fixes:
1. try setting `--projected-ambient-count-threshold 2`... this will greatly limit the number of ATAC features included in the analysis
2. try setting `--posterior-batch-size 64` (the default is 128, and it looks like you just barely overflowed your GPU memory)

The multiome RNA + ATAC data is a challenge for cellbender still, since there are typically close to 200k features!

**Comment by sjfleming** [comment]
Closed by #238

**Comment by zhijunyuu** [comment]
> Hi @zhijunyuu , it looks like you are already using that `sf_dev_0.3.0_postreg` branch, potentially, based on the log file. You can make sure you have the latest version of the changes on that branch by following this:
> 
> [#225 (comment)](https://github.com/broadinstitute/CellBender/issues/225#issuecomment-1667976108)
> 
> I would suggest two potential fixes:
> 
> 1. try setting `--projected-ambient-count-threshold 2`... this will greatly limit the number of ATAC features included in the analysis
> 2. try setting `--posterior-batch-size 64` (the default is 128, and it looks like you just barely overflowed your GPU memory)
> 
> The multiome RNA + ATAC data is a challenge for cellbender still, since there are typically close to 200k features!

Hi,
Thanks for the reply, where can I change the settings of `--projected-ambient-count-threshold` and `posterior-batch-size`? in the infer.py? could you please specify which line? Thanks in advance!

Best,
Zhijun

**Comment by sjfleming** [comment]
Hi @zhijunyuu , sorry, I should have been more clear.  Those things are now command-line arguments for v0.3.0, which was released just last week.

You can get v0.3.0 by doing
```console
pip install cellbender
```
(Make sure you are using python 3.7)

So try installing v0.3.0 and then try running cellbender like this
```console
$ cellbender remove-background \
    --cuda \
    --input my_input_file.h5 \
    --output my_output_file.h5 \
    --projected-ambient-count-threshold 2 \
    --posterior-batch-size 64
```

**Comment by ggconnell** [comment]
Hi there! I'm running into a similar issue. I am running cellbender v0.3.0 on a RTXA5000 GPU device with 24GB of mem with the following line: 
cellbender remove-background --cuda --input 2_alignment/DCK-sc43_alignment/outs/raw_feature_bc_matrix.h5 --output 2_alignment/DCK-sc43_alignment/outs/cellbender_cleaned_feature_bc_matrix.h5  --fpr 0.01 --epochs 150

I keep getting this error:
cellbender:remove-background: Working on chunk (173/476)
cellbender:remove-background: Working on chunk (174/476)
cellbender:remove-background: Working on chunk (175/476)
cellbender:remove-background: Working on chunk (176/476)
slurmstepd: error: Detected 1 oom_kill event in StepId=39347527.0. Some of the step tasks have been OOM Killed.

Small adjustments have just changed at which batch it is failing. 
The .h5 file is 676Mb. Any help would be greatly appreciated. I have been trouble shooting this for over a week.

**Comment by sjfleming** [comment]
@ggconnell , can you try the code on the branch `sf_memory_efficient_posterior_generation` and let me know if it solves the problem for you?  (I'm not sure if it will.  I will be testing on some of my own datasets this week.)

**Comment by sjfleming** [comment]
@zhijunyuu I am not sure why that's happening... I have not seen it before.

From the error, I think it's looking for the `python3` command here 
```
/hpc/pmc_stunnenberg/Zhijun/miniconda3/envs/r4.0.2/bin/python3
```
in your `r4.0.2` conda environment.  I have no idea why that would be happening.  It seems like you are running the command from a conda environment called `cellbender`.

What happens if, in your `cellbender` conda environment, you run this?

```bash
(cellbender) $ jupyter nbconvert --to notebook --allow-errors --execute <path_to_an_existing_IPYNB_notebook_file>
```
where `<path_to_an_existing_IPYNB_notebook_file>` is any jupyter notebook.

**Comment by zhijunyuu** [comment]
@sjfleming 
In deed I was running cellbender in the `cellbender` conda environment. And I do not have conda environment called `r4.0.2`.
When I run the code you suggested on `my.ipynb`, I got a `my.nbconvert.ipynb`file.

**Comment by sjfleming** [comment]
Great news!  Thanks for posting the solution here.
